### ISSUE TITLE
Running LTRPred with udocker

### ISSUE THREAD

**Issue by Ramkyeri** [DerKevinRiehl/transposon_annotation_reasonaTE#10]
Dear Kevin, 

it shows the following errors

43386814-085a-3de5-9412-e014919ca2fa
Error: invalid container name may already exist or wrong format

![image](https://user-images.githubusercontent.com/70749594/161714197-990163df-a05a-4111-bfea-03e73306c62c.png)

with regards

Ramky

**Comment by DerKevinRiehl** [comment]
Dear Ramky,
did you ever use udocker / create a udocker before?
Probably you already have one with a similar name on your system.

Maybe deinstall and reinstall udocker can make the trick?
You should check where udocker is storing the images.

In general: Using LTRPred is not easy, and the tutorials we provide are just our guidance.
Maybe oyu can try to install the tool in your environemnt based on the guidance of the authors from LTRPred, as explained on this site:  https://github.com/HajkD/LTRpred

Can you use docker on your environment? Maybe then you could try it with docker. On our cluster, docker was not allowed, which is why we used udocker.

Please let me know if this could help,
Best regard,
Kevin

**Comment by Ramkyeri** [comment]
Dear Kevin, 
Many thanks. 
First I used docker,   but I did not able to copy the files from docker desktop to local system (and I am using WSL2), 
docker does not work in the conda environment,  so I tried  udocker.  I will follow your suggestion. 

with regards 

Ramky
