### ISSUE TITLE
error in MUST component

### ISSUE THREAD

**Issue by bishopia** [DerKevinRiehl/transposon_annotation_reasonaTE#4]
I'm working through your reasonaTE pipeline now and am having trouble with MUST annotation. Have you seen the following error or know how to correct/fix it? I snagged just the first few lines from stdout, but it goes on forever.... Best, Ian

```
(transposon_annotation_tools_env)[ibishop@node1163 res1]$ reasonaTE -mode annotate -projectFolder workspace -projectName ref_euk -tool must
Spliting the genome into 10 sub-genomes ...  [SubFiles:10] [done] [Elapsed time: 0 seconds]
Scanning the nucleotide sequences for potential MITEs ... Total calculation time elapsed: 561 seconds.
Loading the annotation data ...  [RawMITEs:295] [done] [Time:0 seconds]
Removing redundancy in the predicted MITEs ... Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
Use of uninitialized value $newB in array element at /gpfs/home/ibishop/data/ibishop/condas/transposon_annotation_tools_env/bin/MUST.r2-4-002.Release/MUST_Pipe.pl line 119.
```

**Comment by gqpx** [comment]
I am having the same issue...

**Comment by DerKevinRiehl** [comment]
Dear bishopia and gqpx,
thanks for raising this issue!

Unfortunately, I am not the author of MUST, and just converted MUST into a conda package to integrate it into my tool.

The code can be found here:
https://github.com/DerKevinRiehl/transposon_annotation_tools/blob/main/transposon_annotation_tools_mustv2/MUST.r2-4-002.Release/MUST_Pipe.pl

The "uninitialized value $newB" actually is mentioned in Line 117 and 119.
I am not sure why this error happens.

Could you please give me...
- the FASTA file you were using? I want to try to reproduce the error
- a summary of your CONDA environment, so I can check if there are some version conflicts (e.g. for PERL) (to give me the summary, just export conda environment to yaml using: conda env export --name ENVNAME > envname.yml

Moreover, can you try to run the original MUSTv2 on your machine? 
http://www.healthinformaticslab.org/supp/resources.php
It would be interesting to see if you have the same issue with the original code (I didnt change it a lot).

Thank you very much for your answers in advance,
Best regards,
Kevin

**Comment by gqpx** [comment]
I am using genome GCF_003344945.1 as a test. The genomes for the analysis itself will not be annotated. Please find the summary of our CONDA environment below. I also tried to use a native version of MUST, but the _-tool_ flag only accepts the implemented options.

[envname.txt](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/files/7102000/envname.txt)

**Comment by bishopia** [comment]
The error disappeared when i ran your must tool on GCA_000149405.2. As for the draft assembly I had an issue with, could i send it privately?

**Comment by DerKevinRiehl** [comment]
Dear gqpx and bishopia,
sorry for the late reply and thank you very much for your answers and useful sugestions.
I should be available more from now on with answering Github issues.

### @gqpx
Dear GPQX thanks for sharing your environment. I tried to find differences between [your ENV](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/files/7102000/envname.txt) and [my setup](https://raw.githubusercontent.com/DerKevinRiehl/transposon_annotation_reasonaTE/fc8fdad67bf826cd472ffbfb3f0d047255de5743/environment_yml/transposon_annotation_tools_env.yml), using [https://text-compare.com/de/](https://text-compare.com/de/). What I found is attached to this post in the [Comparison.pdf](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/files/7300056/Comparison.pdf).
What we can find from this comparison (left column is yours, right column is mine) is actually a lot ^^, probably because we have different base environment setups. As MUSTv2 is a perl based tool, I checked the perl conda packages. Except for some very small packages, I dont see lots of differences between our environments.
**I would like you to try to delete the environment and just reinstall it.**
**Could you please try to run it with the demo fasta file that I provide in the tutorial and tell me, if you got the same error again?**

### @bishopia 
I think that is very strange that it works for some genomes, and for others not.
**Are you sure you are getting the same error? Did you retry multiple times?**
From my point of view this error is related to a wrong setup of the conda environment, as its about a syntax problem of the must code itself rather than anything possibly related to the genome.

Best regards,
Kevin Riehl
